#!/bin/bash

if [[ -n $XC_LOCAL_REDIRECTORS ]]; then
    # Tell Supervisor to start up a cmsd process 
    cat <<EOF > /etc/supervisord.d/10-standlone-cmsd.conf
[program:cmsd-standalone]
command=/usr/bin/cmsd -c /etc/xrootd/xrootd-standalone.cfg -k fifo -n xrootd-standalone -k 10 -s /var/run/xrootd/cmsd-standalone.pid -l /var/log/xrootd/cmsd.log
user=xrootd
autorestart=true
EOF

    # Configure XCache to point to the local redirector(s)
    # To specify redirector(s), users should set XC_LOCAL_REDIRECTORS
    # to a comma-delimited list of <FQDN>:<PORT> for each redirector
    XROOTD_CONFIG=/etc/xrootd/config.d/50-generated-cmsd.conf

    echo "# This file automatically generated by XrootD Standalone container startup" > $XROOTD_CONFIG

    IFS=',' read -ra REDIRECTORS <<< "$XC_LOCAL_REDIRECTORS"
    for REDIR in "${REDIRECTORS[@]}"; do
        FQDN=${REDIR%%:*}
        PORT=${REDIR##*:}
        CONFIG_LINE="all.manager $FQDN+ $PORT"
        echo "Writing '$CONFIG_LINE' to /etc/xrootd/config.d/50-generated-cmsd.conf..."
        echo $CONFIG_LINE >> $XROOTD_CONFIG
    done
fi
