#!/bin/python3

import re
import htcondor

def update_user(negotiator, ad):
    current_factor = int(ad["PriorityFactor"])
    new_factor = current_factor

    # ap20/21 migration - users on the old access point
    # will have lower priority to incentivize migration
    if re.search("login0[45].osgconnect.net", ad["Name"]):
        new_factor = 2000

    if new_factor != current_factor:
        user = ad["Name"]
        print(f"Updating {user} from {current_factor} to {new_factor}")
        negotiator.setFactor(user, new_factor)


negotiator = htcondor.Negotiator()
prios = negotiator.getPriorities()

for ad in negotiator.getPriorities():
    try:
        update_user(negotiator, ad)
    except:
        # ignore individual exceptions - we want to try all users
        pass

