#!/bin/bash

# A token.
if [[ -f /root/secrets/token ]]; then
    umask 077
    install -o condor -g condor -m 0600 -D /root/secrets/token /etc/condor/tokens.d/token ||\
        fail "/root/secrets/token found but unable to copy"
    umask 022
fi

# A tokend dir.
if [[ -d /root/secrets/tokens ]]; then
    cp -pv /root/secrets/tokens/* /etc/condor/tokens.d
    chown condor:condor /etc/condor/tokens.d/*
    chmod 0600 /etc/condor/tokens.d/*
fi

# vim:et:sw=4:sts=4:ts=8
