#!/bin/bash

AUTOCONF_FILE="/etc/gwms-factory/OSG_autoconf.yaml"
FACTORY_XMLDIR="/etc/osg-gfactory/"
AUTOCONF_DIR="/var/lib/gwms-factory/OSG_autoconf/"
GENERATED_XMLFILE="10-hosted-ces.auto.xml"
MYTMP=${TMPDIR:-/tmp}

cd $MYTMP
OSG_autoconf "$AUTOCONF_FILE" --skip-broken
if [ $? -ne 0 ]; then
  echo "OSG_autoconf exited with a code different than 0. Aborting."
  echo "Continuing with reconfigure and old xmls"
  exit
fi

echo "Differences with current xml:"
# Use gfdiff when it is fixed
ret=1
diff "$FACTORY_XMLDIR/$GENERATED_XMLFILE" "$AUTOCONF_DIR/$GENERATED_XMLFILE"
if [ $? -ne 0 ]; then
  # Replace only if different
  echo "Moving $AUTOCONF_DIR/$GENERATED_XMLFILE to $FACTORY_XMLDIR/$GENERATED_XMLFILE"
  mv "$AUTOCONF_DIR/$GENERATED_XMLFILE" "$FACTORY_XMLDIR/$GENERATED_XMLFILE"
fi
echo "hostedce_gen.sh has finished"
