FROM centos:7
COPY crontab /etc/crontab
COPY supervisord.conf etc/supervisord.conf
COPY fts3config etc/fts3/fts3config
COPY fts-msg-monitoring.conf etc/fts3/fts-msg-monitoring.conf
COPY docker-entrypoint.sh tmp/docker-entrypoint.sh 
RUN rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
RUN rpm -Uvh https://repo.opensciencegrid.org/osg/3.5/osg-3.5-el7-release-latest.rpm
#ADD "https://dmc-repo.web.cern.ch/dmc-repo/dmc-rc-el7.repo" "/etc/yum.repos.d/"
ADD "http://fts-repo.web.cern.ch/fts-repo/fts3-prod-el7.repo" "/etc/yum.repos.d/"
#ADD "http://fts-repo.web.cern.ch/fts-repo/fts3-rc-el7.repo" "/etc/yum.repos.d/"
RUN yum update -y
RUN yum install epel-release -y
RUN yum install yum-plugin-priorities -y
RUN yum install -y osg-ca-certs
RUN yum install -y fts-server-3.9.5 \
                   fts-client-3.9.5 \ 
                   fts-rest-3.9.4 \ 
                   fts-monitoring-3.9.1 \
                   fts-mysql-3.9.5 \
                   fts-server-selinux-3.9.5 \ 
                   fts-rest-selinux-3.9.4 \ 
                   fts-monitoring-selinux-3.9.1 \
                   fts-msg-3.9.5 \
                   fts-infosys-3.9.5
RUN yum install -y gfal2-all osg-gridftp gfal2-util cronie crontabs supervisor vo-client
# clean up
RUN yum clean all && \
    rm -rf /var/cache/yum
ENTRYPOINT sh tmp/docker-entrypoint.sh
